# Other strategies documentation 

services:
  postgre:
    image: postgres:${POSTGRES_TAG}
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # - ./postgre_vol:/var/lib/postgresql/data  (create a directory at the root of the project and use bind mount)
      - postgre_docker_vol:/var/lib/postgresql/data # use docker managed volume
    networks:
      - kube_news_net

  # For extends another 
  # web:
  #   extends:
  #     file: ./kube_news_compose.yaml
  #     service: kube_news
  #   image: gioufop/kube-news:latest

  # Using include strategy
# include:
#   - ./kube_news_compose.yaml

volumes:
  postgre_docker_vol:
    # external: true # if you want to use a named volume that is not managed by docker, you can set external to true
networks:
  kube_news_net:
    driver: bridge
